name: vintage_1020
description: "An app for tracking consignment inventory."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.5.0
  google_vision: ^2.0.0+6
  url_launcher: ^6.3.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  image_picker: ^1.1.2
  google_sign_in: ^6.3.0
  firebase_ui_auth: ^3.0.0
  firebase_ui_oauth_google: ^2.0.0
  json_annotation: ^4.9.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.0-dev.17
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  fl_chart: ^1.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_image_gallery_saver: ^0.0.2
  photo_gallery: ^2.2.1
  photo_manager: ^3.7.1
  photo_manager_image_provider: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.17
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17
  build_runner: ^2.7.1
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - resources/images-furniture/
    - resources/images-lamps/
    - resources/branding/