// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuDkXcGvZvVXuy6mEcbE5tiNXBQ9nTh9A',
    appId: '1:421198450591:web:7ca41ecce0bc7f051677aa',
    messagingSenderId: '421198450591',
    projectId: 'vintage-1020-498ff',
    authDomain: 'vintage-1020-498ff.firebaseapp.com',
    storageBucket: 'vintage-1020-498ff.firebasestorage.app',
    measurementId: 'G-6GW5PL6LQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLsml_SCyMZg3FqjF5JJ6DZuQGJBG4RVw',
    appId: '1:421198450591:android:d286c8d7121d014a1677aa',
    messagingSenderId: '421198450591',
    projectId: 'vintage-1020-498ff',
    storageBucket: 'vintage-1020-498ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF751iKMVE_a7ESot541SdstHG4BFNMng',
    appId: '1:421198450591:ios:237f8a8e6304daa61677aa',
    messagingSenderId: '421198450591',
    projectId: 'vintage-1020-498ff',
    storageBucket: 'vintage-1020-498ff.firebasestorage.app',
    iosBundleId: 'com.example.vintage1020',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF751iKMVE_a7ESot541SdstHG4BFNMng',
    appId: '1:421198450591:ios:aa4e76809f48704b1677aa',
    messagingSenderId: '421198450591',
    projectId: 'vintage-1020-498ff',
    storageBucket: 'vintage-1020-498ff.firebasestorage.app',
    iosBundleId: 'com.example.vintage1020',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuDkXcGvZvVXuy6mEcbE5tiNXBQ9nTh9A',
    appId: '1:421198450591:web:7ca41ecce0bc7f051677aa',
    messagingSenderId: '421198450591',
    projectId: 'vintage-1020-498ff',
    authDomain: 'vintage-1020-498ff.firebaseapp.com',
    storageBucket: 'vintage-1020-498ff.firebasestorage.app',
    measurementId: 'G-6GW5PL6LQL',
  );
}
